//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEjem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ejemploDbEntities : DbContext
    {
        public ejemploDbEntities()
            : base("name=ejemploDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<perfilUsuario> perfilUsuario { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
        public virtual DbSet<usuarioRoles> usuarioRoles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
