//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webExamen.Data
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.UsuarioRoles = new HashSet<UsuarioRoles>();
        }
    
        public int idUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> suspendido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        public virtual ICollection<UsuarioRoles> UsuarioRoles { get; set; }
    }
}
